# Generated by Django 3.1.13 on 2022-08-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_event_resourceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='resourceId',
            field=models.TextField(),
        ),
    ]
